services:
  - type: web
    name: php-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: mysql-db
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: sua_senha
      - key: DB_NAME
        value: seu_banco
    autoDeploy: true

  - type: pserv
    name: mysql-db
    env: docker
    dockerfilePath: ./mysql/Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: sua_senha
      - key: MYSQL_DATABASE
        value: seu_banco
